modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
[[mods]]
modId="milagresdsmod"
version="1.0.0"
displayName="Milagres DS Mod"

# Required GeckoLib runtime dependency for Forge 1.20.1
[[dependencies.milagresdsmod]]
modId="geckolib"
type="required"
versionRange="[4.7,)"
ordering="NONE"
side="BOTH"
