modLoader="javafml"
loaderVersion="[47,)" # FML 47.x (Forge 1.20.1)
license="All rights reserved"
issueTrackerURL=""

[[mods]]
modId="milagresdsmod"
version="${file.jarVersion}"
displayName="MilagresDS Mod"
authors="Stefani"
description='''
Mod MilagresDS para MC 1.20.1.
'''

[[dependencies.milagresdsmod]]
modId="forge"
mandatory=true
versionRange="[47.4.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.milagresdsmod]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"

[[dependencies.milagresdsmod]]
modId="geckolib"
mandatory=true
versionRange="[4.7,)"
ordering="NONE"
side="BOTH"
